# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-dev python-pip
            sudo pip install awscli

      - run: 
          name: check
          command: aws --version


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test

      # build
      - run: yarn build


      - run:
          name: Deploy
          command: 'aws s3 sync ./build s3://markushanna19 --delete --acl public-read'
      - run:
          name: Clear cloudfront cache
          command: 'aws cloudfront create-invalidation --paths "/*" --distribution-id EOACRN59S25DA'



